### PR TITLE
Added explaination for the garbage collector

### PR DESCRIPTION
**Pull request by janbuecker**

### CODE REVIEW

**Comment by tiagojsag** [comment]
looks fine to me. @MarcelSchmaeing merge if you want

**Comment by janbuecker** [comment]
Please keep in mind that i've opened a new "Shopware 5.1" section without RC suffix.

**Comment by tiagojsag** [comment]
@janbuecker that's why I want @MarcelSchmaeing feedback
I personally think that the document is growing too much, and thus becoming less readable.
As an alternative, we might consider merging everything into a single SW 5.1 section. Now that the RC2 is out, no one should still use RC1. As such, it makes no sense to keep an 5.1 RC1 section, it just clutters the document.

**Comment by tiagojsag** [comment]
@janbuecker we decided to merge RC1 and RC2 (https://github.com/shopware/devdocs/pull/136)

Your new section should be RC3.

**Comment by janbuecker** [comment]
Please wait before merging this PR. There are additions in the core that should be documented.

**Comment by janbuecker** [comment]
Changes have been made. Ready to merge.

**Pull request merged**
