### PR TITLE
Added troubleshooting manual (custom designer component)

### PR DESCRIPTION
**Pull request by wolv-dev**
Added manual for troubleshooting, when custom designer component is not working

### CODE REVIEW

**Comment by bcremer** [comment]
@shopware/shopware-webdev Can one of you please review and merge. Thanks.

**Comment by Phil23** [comment]
Hey,

thx for the hint. Could you please change it to an info alert above the property list? May be like this:

`<div class="alert alert-info">When you want to use a custom component for the designer, it is necessary to define a xtype in the \`createEmotionComponent()\` method for your element.</div>`

Thank you.

**Comment by wolv-dev** [comment]
Hi, should I remove the information about the ExtJS part and only add the info alert? Or should I rewrite it to use both?

**Comment by Phil23** [comment]
Hey,

I think the alert message should be enough.

thx!

**Comment by wolv-dev** [comment]
Done!

**Comment by Phil23** [comment]
Thx!

**Pull request merged**
