### PR TITLE
SW-12513 - Added tutorial: Custom detail page

### PR DESCRIPTION
**Pull request by tobiasberge**
In-depth tutorial for customizing the detail page template.

### CODE REVIEW

**Comment by tobiasberge** [comment]
@klarstil & @tiagojsag would please have a look at this tutorial?

**Comment by tiagojsag** [comment]
I already reviewed the article, seems ok to me. I have a local commit with minor typo fixes, nothing too important. 

I think it would make sense to create a small plugin with the end result of these changes. I see a lot of small, individual code blocks in the article, which can become confusing/frustrating to the end user.

@klarstil what do you think?

**Comment by klarstil** [comment]
Great tutorial, I like how you structure it and how you guide the reader through it. Good job!

**Comment by tiagojsag** [comment]
@tobiasberge Demo plugins should go in the /exampleplugins folder, uncompressed. The deploy script will automatically create the zip file.

Also, I would prefer to have the install instructions using the backend plugin manager. less change for people messing up

**Pull request merged**
