### PR TITLE
New Docs

### PR DESCRIPTION
**Pull request by Anshul8j**

### CODE REVIEW

**Review by mitelg — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for your contribution @Anshul8j  :+1: :tada: :blue_heart:

**Comment by Anshul8j** [comment]
> thanks for your contribution @Anshul8j 👍 🎉 💙

So please kindly pass my pull request

**Comment by mitelg** [comment]
what do you mean? it is merged?

**Comment by Anshul8j** [comment]
Yaa that's what I want to say, accept my PR my merging it please....

**Pull request merged**
