### PR TITLE
Upgrade guide for sw 5.1

### PR DESCRIPTION
**Pull request by tiagojsag**
Upgrade guide for SW 5.1

### CODE REVIEW

**Comment by dnoegel** [comment]
@tiagojsag We should have one distinct upgrade document / article per shopware release (e.g. 5.0, 5.1). We can have an own "upgrade guides" section in the "development" section.

Adding it all to a single document is a bit bloaty, I think

**Comment by tiagojsag** [comment]
@dnoegel I share your opinion, but @MarcelSchmaeing doesnt ;)

**Comment by dnoegel** [comment]
No problem, I will silently fix it next week :)

**Comment by tiagojsag** [comment]
do a slient PR, I will silently review it and silently merge it

**Comment by dnoegel** [comment]
:+1:  :)

**Pull request merged**
