### PR TITLE
fix syntax

### PR DESCRIPTION
**Pull request by buddhaCode**
Attribute names will be parsed vom snake case (html) to camel case (js).

### CODE REVIEW

**Comment by mitelg** [comment]
hey @buddhaCode 
snake case is with _ underscore. 
Afaik `example-value` and `exampleValue` are two different things. Although if you write `data-exampleValue` in your smarty code, the output will be `data-examplevalue`
So with your change, the example won't work, imho.

**Comment by buddhaCode** [comment]
I mean dash case. Sorry.

And yes, your right. I proposed a pull request here: https://github.com/shopware/shopware/pull/1477
I just referred to this PR on the docs: https://github.com/shopware/devdocs/pull/758
The example in this PR doesn't work either.

**Comment by mitelg** [comment]
ok, I think we have to talk about that thing internally (looking at you @klarstil :wink: )

If your PR gets merged, we should adjust the docs after that. I would like to close your PR, as your change would not work as intended. Is this ok for you?

**Comment by buddhaCode** [comment]
It's fine. :)

**Pull request closed without merging**
