### PR TITLE
added Plugin to expand/collapse large code tags.

### PR DESCRIPTION
**Pull request by arnoldstoba**

### CODE REVIEW

**Comment by tiagojsag** [comment]
Functionally it works as intended.
@klarstil can you take a look at this please?

**Comment by bcremer** [comment]
@arnoldstoba @tiagojsag can you please leave a usage example as a comment here?

**Comment by tiagojsag** [comment]
http://gyazo.com/b200a6df84aab06bcbe74ed867cea043
Currently is used automatically in all code blocks that exceed a certain preconfigured height

**Comment by bcremer** [comment]
OK tested this feature and I generally like it.

- Can we please increase `maxHeight` to 350px or so.
- The expand "Button" is a bit bulky and uses value space for it self. can we find another solution for the button. eg. float on the right bottom of the code box with 20% width or so.

**Comment by klarstil** [comment]
@arnoldstoba I checked the code and the style. It looks good for me so far.

I agree with @bcremer. The button is way too big, we should consider another solution

**Comment by arnoldstoba** [comment]
Updated the button style and maxHeight (to 370px) in the latest commit.
http://gyazo.com/922f5111252e8ec52cc106ce7b9c8227

**Pull request merged**
