### PR TITLE
Update docs for edb beta2

### PR DESCRIPTION
**Pull request by dnoegel**
@linushstge Can you please update the screenshots with your fancy mac thingy?

### CODE REVIEW

**Comment by bcremer** [comment]
@dnoegel can we get some ‎Amiga 500 screenshots too?

**Comment by teiling88** [comment]
@bcremer i think some ascii art like http://wttr.in/ would be nice too

**Comment by dnoegel** [comment]
I always wanted to provide just boring informational screenshots, but @linushstge told me, that everything looks better with a Mac window and drop shadow around. So he became our PIG (picture-image-generator)

**Comment by bcremer** [comment]
IDrop Shadow

**Comment by linushstge** [comment]
Drop Shadow the right way
Drop Shadow the right way 😤

**Comment by bcremer** [comment]
IDrop Shadow

**Comment by linushstge** [comment]
@dnoegel done.

**Pull request merged**
