### PR TITLE
Graph based recommendation engine

### PR DESCRIPTION
**Pull request by dnoegel**

### CODE REVIEW

**Comment by tiagojsag** [comment]
@dnoegel http://memegenerator.net/instance/64679010

**Comment by tiagojsag** [comment]
@dnoegel reviewed, changes are in my commit, don't forget to include them when you rebase
@bcremer blog post here, you shoud schedule the publication date

**Comment by bcremer** [comment]
@dnoegel 2015-10-14 seems to be a good publish date. Can you please squash before merge?

**Comment by dnoegel** [comment]
Hey @tiagojsag thanks for your effort, really appreciate the corrections.
@bcremer Jawoll, just did that, should be ready to merge

**Pull request merged**
