### PR TITLE
Fixed multiple quote typos

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
There are multiple quote types which lead to invalid code snippets
And an other bracket typo

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
@mitelg you were a bit fast :running_man: Otherwise #871 would have some more amends :blush: I missed these typos in the first reading.

**Comment by mitelg** [comment]
@JoshuaBehrens I'm a simple man, I see PR, I merge :smile:

**Comment by mitelg** [comment]
thanks again @JoshuaBehrens :+1: :tada: :blue_heart:

**Comment by buddhaCode** [comment]
@mitelg 

> I see PR, I merge

I wish your fellas at shopware/shopware would merge PRs a bit more like you do. :)

**Pull request merged**
