### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by wildi1**
It was not clear, to start the Test from the tests folder

### CODE REVIEW

**Comment by mitelg** [comment]
hi @wildi1 
as the `phpunit.xml.dist` file is located in the plugin root directory, you have to start phpunit from there. so in my opinion everything is fine in the article. 
If you are struggling with something, just let me know :blush:

**Comment by wildi1** [comment]
hi@mitelg,
below the Basics headline is written:

> Basics
> The starting point for testing your own plugin ist the **phpunit.xml[.dist]_ and the Bootstrap.php file in the \tests** folder of your plugin.

**Comment by mitelg** [comment]
ok, maybe this is written a bit misleading. At the end of the article you will find an example plugin for download. There you can see where this files are located. I will update the article to fix the confusion :wink:

**Comment by mitelg** [comment]
https://github.com/shopware/devdocs/pull/658

**Pull request closed without merging**
